name: Mack and Mike in the morning
title: Mack and Mike in the morning
email: mackandmikeinthemorning@gmail.com
url: "https://mackandmikeinthemorning.com/"
itunes_summary: Mack and Mike talk about life, tech, and the tech lifestyle.
description: Mack and Mike talk about life, tech, and the tech lifestyle.
author: Mack and Mike
itunes_owner_name: Mike Chow
itunes_owner_email: mchow815@gmail.com
lang: en-us
explicit: no
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
podcast_audio_prefix: "https://s3.us-east-2.amazonaws.com/mackandmike/audio/"
collections:
 podcasts:
  output: true 
